
MYSQL_HOST = "127.0.0.1"
MYSQL_USERNAME = "root"
MYSQL_PASSWORD = "root"
MYSQL_DB = "ndoutils"


CLOUD_MONITOR_MYSQL_HOST = "172.16.0.207"
CLOUD_MONITOR_MYSQL_USERNAME = "root"
CLOUD_MONITOR_MYSQL_PASSWORD = "cloudopen"
CLOUD_MONITOR_MYSQL_DB = "cloud_monitor"
